"""
Django settings for identity_service project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Import os to read environment variables
from datetime import timedelta
import os

# Import load_dotenv to load values from .env file
from dotenv import load_dotenv

# Build path to current project base directory
from pathlib import Path

# Base directory of project
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")

# Basic logging configuration for learning and debugging request flow
LOGGING = {
    # Version is required by Django logging config format
    "version": 1,
    # Keep existing Django loggers active unless we override them
    "disable_existing_loggers": False,
    # Define how logs should look when printed in terminal
    "formatters": {
        "standard": {
            # Include level, time, logger name, and message
            "format": "%(levelname)s | %(asctime)s | %(name)s | %(message)s",
        },
    },
    # Define where logs are sent
    "handlers": {
        "console": {
            # Send logs to terminal/console
            "class": "logging.StreamHandler",
            # Use the formatter defined above
            "formatter": "standard",
        },
    },
    # Root logger config
    "root": {
        # Minimum level to show
        "level": "INFO",
        # Send root logs to console
        "handlers": ["console"],
    },
}
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Tell Django to use our custom Account model instead of the default auth.User
AUTH_USER_MODEL = "accounts.Account"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "apps.accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "identity_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "identity_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
ENVIRONMENT = os.getenv("ENVIRONMENT", "local")

if ENVIRONMENT == "docker":
    DB_HOST = "db"
    DB_PORT = "3306"
else:
    DB_HOST = os.getenv("DB_HOST", "127.0.0.1")
    DB_PORT = os.getenv("DB_PORT", "3307")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME", "commerce_identity_db"),
        "USER": os.getenv("DB_USER", "root"),
        "PASSWORD": os.getenv("DB_PASSWORD", "rootpassword"),
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        "TEST": {
            "NAME": "test_commerce_identity_db",
        },
    }
}


# Django REST Framework config
# Django REST Framework configuration for identity-service
# Django REST Framework configuration for identity-service
REST_FRAMEWORK = {
    # JWTAuthentication reads Authorization: Bearer <token>
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    # Default permission requires login unless view overrides it
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# SimpleJWT configuration for identity-service
SIMPLE_JWT = {
    # Secret key used to sign JWT tokens
    "SIGNING_KEY": os.getenv("JWT_SECRET_KEY", SECRET_KEY),

    # Algorithm used for token signing
    "ALGORITHM": os.getenv("JWT_ALGORITHM", "HS256"),

    # Access token lifetime for development
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),

    # Refresh token lifetime
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib."
        "auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
