"""
Django settings for product_service project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Import os to read environment variables
from datetime import timedelta
import os

# Import Path to build file paths safely
from pathlib import Path

# Import load_dotenv to load values from .env file
from dotenv import load_dotenv

# Base directory of this Django project
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=(*r5+ip+z83fh^760waczpqu!i$*8l%go0p*+e#@$myx@3p=y"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "apps.catalog",
    "django_filters",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "product_service.urls"


# SimpleJWT configuration for identity-service
SIMPLE_JWT = {
    # Secret key used to sign JWT tokens
    "SIGNING_KEY": os.getenv("JWT_SECRET_KEY", SECRET_KEY),
    # Algorithm used to sign JWT tokens
    "ALGORITHM": os.getenv("JWT_ALGORITHM", "HS256"),
    # Access token valid duration
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    # Refresh token valid duration
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}
# Django REST Framework global configuration

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    # Enable filtering, search, and ordering globally
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # Enable pagination globally
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # Default records per page
    "PAGE_SIZE": 10,
}


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "product_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration for product-service
DATABASES = {
    # Default database connection used by Django ORM
    "default": {
        # Use MySQL database engine
        "ENGINE": "django.db.backends.mysql",
        # Database name from .env file
        "NAME": os.getenv("DB_NAME", "commerce_product_db"),
        # Database user from .env file
        "USER": os.getenv("DB_USER", "root"),
        # Database password from .env file
        "PASSWORD": os.getenv("DB_PASSWORD", "rootpassword"),
        # Database host from .env file
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        # Database port from .env file
        "PORT": os.getenv("DB_PORT", "3307"),
        # Test database config used during Django test execution
        "TEST": {
            # Separate database name for automated tests
            "NAME": "test_commerce_product_db",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
